name: Build & Publish Artifacts

on:
  workflow_dispatch:         # Manual trigger
  push:
    tags:
      - 'v*.*.*'             # Tag pattern like v1.2.3
  release:
    types: [created]         # When a GitHub Release is manually created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JARs to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drop-jars
          path: build/libs/*.jar   # Wildcard for all jars in build/libs

  publish_release_assets:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download JARs from Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop-jars
          path: artifacts/         # Download into artifacts/ directory

      - name: Ensure GitHub Release
        id: ensure_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JARs to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.ensure_release.outputs.upload_url }}
          asset_path: artifacts/*.jar
          asset_name: ${{ github.ref_name }}-${{ github.run_id }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
